#!/usr/bin/env python3
"""Preview or copy the optional Linear/Symphony WORKFLOW.md template.

All other Codex project files should be generated by the agent at runtime from
the inspected repository context and user decisions, not by this script.
"""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parents[1]
WORKFLOW_TEMPLATE = SKILL_DIR / "assets" / "WORKFLOW.linear.template.md"


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def diff_for_file(repo: Path, rel: Path, new_content: str) -> str:
    path = repo / rel
    old_content = read_text(path)
    old_lines = old_content.splitlines(keepends=True)
    new_lines = new_content.splitlines(keepends=True)
    fromfile = str(rel) if path.exists() else f"/dev/null ({rel})"
    return "".join(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=fromfile,
            tofile=str(rel),
            lineterm="\n",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Repository root")
    parser.add_argument("--linear", action="store_true", help="Preview or write optional Linear/Symphony WORKFLOW.md")
    parser.add_argument("--dry-run", action="store_true", help="Print proposed WORKFLOW.md unified diff")
    parser.add_argument("--write", action="store_true", help="Write WORKFLOW.md")
    args = parser.parse_args()

    repo = args.repo.resolve()
    if not repo.exists():
        raise SystemExit(f"Repository does not exist: {repo}")
    if args.write and args.dry_run:
        raise SystemExit("Use either --dry-run or --write, not both.")
    if not args.linear:
        raise SystemExit("This script only handles optional WORKFLOW.md. Pass --linear when the user wants Linear/Symphony workflow files.")
    if not args.write:
        args.dry_run = True

    content = read_text(WORKFLOW_TEMPLATE)
    if not content:
        raise SystemExit(f"Missing template: {WORKFLOW_TEMPLATE}")

    rel = Path("WORKFLOW.md")
    if args.dry_run:
        print(diff_for_file(repo, rel, content).rstrip())
        return 0

    write_text(repo / rel, content)
    print(f"Wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
